version: "3.6"
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
            cache_from:
                - ncov2019scrapy:dev
        # volumes: 
        #     - ./:/usr/src/app            
        ports:
            - "6800:6800"
    influxdb:
        image: influxdb:1.7.6
        volumes: 
            - influxdata:/var/lib/influxdb
        ports:
            - "8086:8086"
    grafana:
        image: grafana/grafana:5.4.3
        volumes: 
            - grafana-data:/var/lib/grafana
            - grafana-plugins:/var/lib/grafana/plugins
        ports:
            - "3000:3000"
        environment: 
            - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel"
    corenlp:
        image: hysios/corenlp:dev
        ports:
            - "9001:9001"
volumes: 
    influxdata:
    grafana-data:
    grafana-plugins:
    # elastic-data:
